examples/only_get.py, src/response.rs
This pull request includes changes to the `examples/only_get.py` and `src/response.rs` files. The most important changes involve updating the response handling in the `Response` struct and adding new functionalities.
* [`src/response.rs`](diffhunk://#diff-6f9f8f882acd334c5bf0b598b309afef5f90f63d20b4cc6c26751d66bcb1dba6R276-R288): Added a new `inner` method to provide access to the inner `rquest::Response` wrapped in an `Arc`. This method helps in accessing the original response object directly.
* [`src/response.rs`](diffhunk://#diff-6f9f8f882acd334c5bf0b598b309afef5f90f63d20b4cc6c26751d66bcb1dba6L81-R83): Modified the `headers` getter method to return a `PyResult<HeaderMap>` instead of `HeaderMap`, utilizing the new `inner` method.
* …
=> feat(response): Add cookies support

examples/only_get.py, examples/only_req.py, src/resp.rs
This pull request includes several changes to the `examples/only_get.py`, `examples/only_req.py`, and `src/resp.rs` files. The most important changes involve modifying the `impersonate` parameter, updating the response connection closing method, and simplifying the `close` method in the `Response` implementation.
* Updated the `impersonate` parameter from `Impersonate.Chrome104` to `Impersonate.Chrome100`.
* Modified the commented-out response connection closing method from `await resp.close()` to `resp.close()`.
* Modified the commented-out response connection closing method from `await resp.close()` to `resp.close()`.
* Simplified the `close` method in the `Response` implementation by removing the asynchronous handling and directly dropping the response.
=> perf(resp): Improve drop response overhead

Cargo.toml, src/resp.rs
This pull request introduces several changes to the `Response` struct and its implementation in the `src/resp.rs` file to improve its handling of internal state and simplify the code. The most important changes include adding the `arc-swap` dependency, updating the `Response` struct to use `ArcSwapOption`, and modifying various methods to work with the new internal structure.
Dependency Addition:
* Added `arc-swap = "1.7.1"` to `Cargo.toml` to enable atomic swapping of `Arc` pointers.
Struct and Field Updates:
* Updated the `Response` struct to include a `url` field and replaced the `response` field with an `ArcSwapOption<rquest::Response>`.
Method Modifications:
* Modified the `impl From<rquest::Response> for Response` to initialize the new fields and use `ArcSwapOption::from_pointee` …
=> feat(resp): Allows thread-safe operation of Response

src/client.rs, src/param/client.rs
This pull request introduces changes to the `Client` and `ClientParams` structures to add support for cookie store options. The most important changes include adding the `cookie_store` option to the `ClientParams` structure and ensuring it is properly applied in the `Client` implementation.
Enhancements to `Client` and `ClientParams`:
* [`src/client.rs`](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R114-R116): Added the application of the `cookie_store` option in the `Client` implementation.
* [`src/param/client.rs`](diffhunk://#diff-ad245d448ef30d353626c3c90a1d5058b600666084be5cd25b43a6f9911f2e11R56-R59): Added the `cookie_store` field to the `ClientParams` structure with appropriate documentation and getter method.
* …
=> feat(client): Add cookie store option

README.md, rnet.pyi, src/client.rs, src/param/client.rs
This pull request includes updates to the `README.md` file, enhancements to the `ClientParams` class, and modifications to the `Client` implementation in `src/client.rs`. The changes aim to improve the initialization process, add new configuration options, and enhance the client functionality.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L82-R82): Updated instructions to clarify the environment initialization and release processes. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L82-R82) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L99-R99)
* [`rnet.pyi`](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eR309): Added …
=> feat(client): Add redirect option

.github/build.sh, .github/workflows/ci.yml, .github/workflows/style.yml, README.md, examples/client.py
This pull request includes changes to support building manylinux wheels, updates to the README for clarity, and minor code cleanup in an example file. The most important changes are summarized below:
* [`.github/build.sh`](diffhunk://#diff-01777b8211405b5ca734f053a69b200b01d7d3b1fb10fbdb337cff18417438f5L4-R11): Added an optional `manylinux` argument to the build script and modified the `MATURIN_CMD` to support building manylinux wheels when this argument is provided. [[1]](diffhunk://#diff-01777b8211405b5ca734f053a69b200b01d7d3b1fb10fbdb337cff18417438f5L4-R11) [[2]](diffhunk://#diff-01777b8211405b5ca734f053a69b200b01d7d3b1fb10fbdb337cff18417438f5R31-R35)
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL36-R36): Updated the CI …
=> build: Fix manylinux build

rnet.pyi, src/lib.rs, src/resp.rs, src/types/mod.rs, src/types/status_code.rs
This pull request includes changes to the `Response` class in the `rnet.pyi` file and the `Response` implementation in the `src/resp.rs` file. The main focus of these changes is to update the type of the `status_code` attribute and simplify its getter method.
Type update:
* [`rnet.pyi`](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eL550-R550): Changed the type of `status_code` from `typing.Any` to `builtins.int`.
Getter method simplification:
* [`src/resp.rs`](diffhunk://#diff-9a3d8ee28d27cfa8b2299e506a0a95487f26e9e67b282b93f7cf4987f559cf16L93-R94): Simplified the `status_code` getter method by returning the status code directly as a `u16` instead of creating a Python object.
=> feat(resp): Wrapper easy-to-use `StatusCode`

src/client.rs, src/lib.rs, src/param/req.rs, src/types/mod.rs
This pull request includes several changes to improve the handling of request parameters and macro definitions in the Rust codebase. The most important changes include adding support for redirect options, moving a macro definition, and updating the `RequestParams` struct and its implementation.
Improvements to request parameters:
* [`src/client.rs`](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R606-R615): Added support for redirect options in the `execute_request` function by applying the `allow_redirects` parameter.
* [`src/param/req.rs`](diffhunk://#diff-586db287f66766708a28ea51faf15b6701148458f588aac618223bc2f457fe92R65-R67): Updated the `RequestParams` struct to include an `allow_redirects` field and modified the `FromPyObject` implementation to …
=> feat: Shortcut method request support redirect

rnet.pyi, src/client.rs, src/lib.rs, src/resp.rs
This pull request includes several changes to the `Response` class and related files to improve type safety and performance. The most important changes include modifying the `stream` method to return a `Streamer` type, adding the `Streamer` class to the module, and optimizing getter methods for the `Response` class.
Changes to type safety and method signatures:
* [`rnet.pyi`](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eL631-R631): Modified the `stream` method in the `Response` class to return a `Streamer` type instead of `typing.Any`.
* [`src/resp.rs`](diffhunk://#diff-9a3d8ee28d27cfa8b2299e506a0a95487f26e9e67b282b93f7cf4987f559cf16L287-R295): Updated the `stream` method in the `Response` class to return a `Streamer` instance.
Module and class …
=> feat(resp): Expose `Streamer` as public API

src/lib.rs
This pull request includes a small change to the `src/lib.rs` file. The change modifies the `#[pymodule]` attribute to specify that the Global Interpreter Lock (GIL) is not used.
* [`src/lib.rs`](diffhunk://#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L258-R258): Modified the `#[pymodule]` attribute to `#[pymodule(gil_used = false)]` to indicate that the GIL is not used.
=> perf: Initialize and optimize Python module without requiring GIL

src/resp.rs
This pull request includes several changes to the `src/resp.rs` file, focusing on improving the handling of response cookies and TLS peer certificates. The most important changes include replacing the `PyDict` with `IndexMap` for cookies, modifying the `peer_certificate` method to return a `Vec<u8>`, and updating the imports to include `IndexMap` and `TlsInfo`.
* Replaced the `PyDict` with `IndexMap` for the `cookies` method to improve the handling of response cookies.
* Modified the `peer_certificate` method to return a `Vec<u8>` instead of a Python object, simplifying the retrieval of the TLS peer certificate.
* Added `indexmap::IndexMap` to the imports to support the new `cookies` method implementation.
* Added `rquest::TlsInfo` to the imports to support the updated `peer_certificate` …
=> perf(resp): Reduce the range of GIL locks

.github/workflows/ci.yml, tests/compression_test.py
This pull request includes new tests for verifying compression methods in the `tests/compression_test.py` file. The most important changes are the addition of three asynchronous test functions to validate gzip, deflate, and brotli compression.
New tests for compression methods:
* Added `test_gzip` function to verify gzip compression by checking the presence of the word "gzipped" in the response text.
* Added `test_deflate` function to verify deflate compression by checking the presence of the word "deflated" in the response text.
* Added `test_brotli` function to verify brotli compression by checking the presence of the word "brotli" in the response text.
=> test: Add decompress tests

rnet.pyi, src/response.rs
This pull request includes several formatting changes to the `rnet.pyi` file and a functional addition to the `src/response.rs` file. The changes in `rnet.pyi` primarily involve the removal of blank lines and minor adjustments to class definitions, while the `src/response.rs` file introduces a new method to the `Response` class.
Formatting changes in `rnet.pyi`:
* Removed blank lines between class definitions and within class bodies to improve readability. [[1]](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eL11) [[2]](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eR275) [[3]](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eL305) [[4]](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea …
=> feat(response): Return an integer representing the HTTP status code

examples/base_url.py, rnet.pyi, src/client.rs, src/param/client.rs
This pull request includes several changes to add support for a base URL parameter in the `Client` class, enhance the WebSocket documentation, and update the related Rust structures. The most important changes include adding the `base_url` parameter, updating the `Client` class, and adding an example script demonstrating the new functionality.
* [`rnet.pyi`](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eR341): Added `base_url` as an optional string parameter to the `ClientParams` class.
* [`src/param/client.rs`](diffhunk://#diff-ad245d448ef30d353626c3c90a1d5058b600666084be5cd25b43a6f9911f2e11R53-R56): Added `base_url` field to the `ClientParams` struct and updated the `FromPyObject` implementation to extract this new parameter. …
=> feat: Add base url for client

Cargo.toml, rnet.pyi, src/client.rs, src/error.rs, src/lib.rs, src/param/client.rs, src/param/mod.rs, tests/client_test.py
This pull request includes several changes to improve the functionality and maintainability of the `rnet` library. The changes focus on enhancing the `Client` class, adding new functionality, and improving error handling.
* Added new methods `get_cookies`, `set_cookies`, and `update` to the `Client` class in `rnet.pyi` to manage cookies and update client parameters.
* Modified `Client` struct to use `ArcSwap` for thread-safe updates and added new methods to retrieve user agent and headers in `src/client.rs`. [[1]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1L47-R53) [[2]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1L627-R854)
* Updated HTTP request methods to use the `load` method of `ArcSwap` for better performance …
=> feat(client): Added thread-safe update client

Cargo.toml, examples/client.py, src/client.rs, src/dns.rs, src/error.rs, src/lib.rs, src/param/client.rs
This pull request introduces several important changes to the `rnet` project, focusing on the addition of an asynchronous DNS resolver and improvements to the existing codebase. The most significant changes include modifications to the `Cargo.toml` dependencies, updates to the `Client` struct to support async DNS, and the addition of a new `dns` module.
* [`src/client.rs`](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R2): Imported the `dns` module and added async DNS resolver initialization in the `Client` struct. [[1]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R2) [[2]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R16) [[3]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86 …
=> feat(client): Optionally enable asynchronous DNS resolver

Cargo.toml, README.md, examples/logger.py, src/dns.rs, src/lib.rs
This pull request introduces several significant changes to the `rnet` project, including the addition of logging features, updates to dependencies, and enhancements to the documentation and examples. The most important changes are outlined below:
* Added a new `[features]` section to `Cargo.toml` to include optional logging dependencies (`pyo3-log` and `log`) [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R17-R19) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R31-R33).
* Updated `src/lib.rs` to conditionally use the `log` and `pyo3_log` crates for logging when the `logging` feature is enabled [[1]](diffhunk://#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R9-R14) …
=> feat: Added bridge from Rust to Python logging

src/client.rs
This pull request includes several changes to the `Client` implementation in the `src/client.rs` file, primarily focusing on refactoring the `default` method and updating imports. Below are the most important changes:
* **Refactored `Client` default implementation**: The `default` method was moved from an `impl Default for Client` block to a static method within the `Client` implementation. This new method initializes a `Client` with default settings, including disabling Hickory DNS and keepalive. [[1]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R59-R95) [[2]](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1L859-L882)
* **Updated imports**: The `std` imports were refactored to include `LazyLock` in a nested manner, …
=> perf(client): Reuse default client to improve quick request efficiency

examples/client.py, examples/logger.py, rnet.pyi, src/types/proxy.rs, tests/client_test.py
This pull request introduces several improvements and new features to the `rnet` library, including enhanced logging, proxy support, and code formatting adjustments. The most important changes include adding logging capabilities, extending proxy support, and making various formatting adjustments in the codebase.
* [`examples/client.py`](diffhunk://#diff-11c528f6f45c94140909cbbc80d8934cd6617f9000e65253e70784bc250a694fL2-R53): Introduced logging using the `colorlog` library to provide colored log output for different log levels.
* [`examples/client.py`](diffhunk://#diff-11c528f6f45c94140909cbbc80d8934cd6617f9000e65253e70784bc250a694fL2-R53): Added support for HTTP and HTTPS proxies with authentication and exclusion options.
* [`src/types/proxy.rs`](diffhunk://#diff-7761cf62502704e7c30c2f7556 …
=> feat(proxy): Enhanced proxy settings binding

rnet.pyi, src/client.rs, src/param/websocket.rs
This pull request includes several enhancements to the WebSocket configuration in the `src/client.rs` and `src/param/websocket.rs` files. The changes focus on adding new configuration options for WebSocket parameters and ensuring they are properly applied during WebSocket requests.
* Added new WebSocket configuration options to the `WebSocketParams` structure, including `write_buffer_size`, `max_write_buffer_size`, `max_message_size`, `max_frame_size`, and `accept_unmasked_frames`. These options provide more control over WebSocket behavior, such as buffer sizes and message handling.
* Updated the `FromPyObject` implementation for `WebSocketParams` to extract the new configuration options from Python objects. This ensures that the new parameters can be set from Python code.
* Modified the …
=> feat: Added websocket optional config

Cargo.toml, examples/stream.py, rnet.pyi, src/client.rs, src/response/http/mod.rs, src/response/http/stream.rs, src/response/ws.rs, tests/resp_test.py
This pull request includes several important changes to improve the handling of asynchronous streaming and simplify the codebase. The main changes involve updating the `Client` and `Response` classes, as well as renaming and refactoring files.
* [`examples/stream.py`](diffhunk://#diff-11a1e7484ffc8ae4532af97bd17cb36187f2fa50fa68111c2d69984c980d2c8cL15-R15): Updated the `main` function to use an asynchronous context manager for streaming.
* [`rnet.pyi`](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eR1009-R1014): Added `__aenter__` and `__aexit__` methods to the `Streamer` class to support asynchronous context management.
* [`src/client.rs`](diffhunk://#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1L137-R138): Simplified the `Client` …
=> perf(http): Optimize the overhead of boundary checks for streaming types

Cargo.toml, pyproject.toml
This pull request includes changes to expand the compatibility of the project to older Python versions and adjust the dependencies accordingly.
Compatibility updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L26-R26): Changed the `abi3` feature from `py39` to `py37` to support Python 3.7 and above.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R13): Updated the `requires-python` field to `>=3.7` and added classifiers for Python 3.7 and 3.8.
=> build: Minimum required Python version is 3.7

rnet.pyi, src/client/mod.rs, src/dns.rs, src/lib.rs, src/param/client.rs, src/types/dns.rs, src/types/mod.rs
This pull request introduces several changes to the `rnet.pyi` and Rust files to add support for a new `LookupIpStrategy` enumeration and improve DNS resolver configuration. The most important changes include adding the `LookupIpStrategy` enum, updating the `ClientParams` and `Client` structures to use this new strategy, and modifying the DNS resolver initialization to accommodate the new strategy.
* Added `LookupIpStrategy` enum to specify different IP lookup strategies, including `Ipv4Only`, `Ipv6Only`, `Ipv4AndIpv6`, `Ipv6thenIpv4`, and `Ipv4thenIpv6`. (`rnet.pyi`, `src/types/dns.rs`, `src/types/mod.rs`) [[1]](diffhunk://#diff-5db1607ce9c6dc00847ecf786751d151324bea51f62f7baf42b71b20603dbf4eR1228-R1237) [[2]](diffhunk://#diff-7be0378b4680ba283c497dedeaa7fd54358d6072cde3fae4d412ba360f7176 …
=> feat(client): Optional DNS lookup ip strategy

.github/workflows/ci.yml, README.md, pyproject.toml
close: https://github.com/0x676e67/rnet/issues/141
=> build: add free-threaded package support

pyproject.toml, rnet.pyi, src/async_impl/client.rs, src/blocking/client.rs, tests/client_test.py
Allowing inheritance of the `Client` and `BlockingClient` class enables customization on user-level which is not necessary to add in the `rnet` module.
=> feat: allow inheritance of Client and BlockingClient in python

src/async_impl/client.rs, src/async_impl/request.rs, src/async_impl/response/http.rs, src/async_impl/response/ws/message.rs, src/async_impl/response/ws/mod.rs, src/blocking/response/http.rs, src/blocking/response/ws.rs, src/error.rs, src/typing/cookie.rs, src/typing/headers.rs, src/typing/multipart/form.rs, src/typing/multipart/part.rs, src/typing/proxy.rs
This pull request focuses on refactoring error handling throughout the codebase by consolidating various error types into a single `Error` type. The changes involve updating error handling in multiple files and functions to use this new consolidated error type.
* [`src/async_impl/client.rs`](diffhunk://#diff-0df5342f97493f9f55d6f43a14268f327ea9e791c7fdb8df6d88ec81f6baa721L6-R10): Replaced specific error handling functions like `wrap_rquest_error` and `wrap_url_parse_error` with the consolidated `Error` type. [[1]](diffhunk://#diff-0df5342f97493f9f55d6f43a14268f327ea9e791c7fdb8df6d88ec81f6baa721L6-R10) [[2]](diffhunk://#diff-0df5342f97493f9f55d6f43a14268f327ea9e791c7fdb8df6d88ec81f6baa721L594-R596) [[3]](diffhunk://#diff-0df5342f97493f9f55d6f43a14268f327ea9e791c7fdb8df6d88ec81f6baa721L638-R …
=> chore(error): refactor exception error handling

src/typing/json.rs
This pull request includes a change to the `Json` enum in the `src/typing/json.rs` file. The change updates the return value of the `type_output` method to use a more specific type representation.
* [`src/typing/json.rs`](diffhunk://#diff-ca3c654de0fbfb9d5c05141294e7b9d5d50041350008bfaf4fe060d1560fedebL20-R20): Modified the `type_output` method to return `TypeInfo::with_module("typing.Dict[str, typing.Any]", "typing".into())` instead of `TypeInfo::any()`.
=> docs(json): Improve `Json` type hints

rnet.pyi, src/typing/json.rs, src/typing/status.rs
This pull request includes several changes to improve type annotations and refactor code for better readability and maintainability. The most important changes include updating type annotations for JSON-related methods and modifying the `__repr__` method for the `StatusCode` implementation.
Code refactoring:
* [`src/typing/status.rs`](diffhunk://#diff-2e249aaa933bd6f06dcd1669446f61c21740a93696b5ca5325ca2f5c3092ea0cL59-R60): Refactored the `__repr__` method in the `StatusCode` implementation to return the result of the `__str__` method.
=> docs(status): Improve StatusCode `__repr__` implement

Cargo.toml, rnet.pyi, src/error.rs, src/lib.rs
close: https://github.com/0x676e67/rnet/issues/189
=> feat(error): fix and export exceptions

src/async_impl/client.rs
from: https://github.com/0x676e67/rnet/issues/191
This follows the browser style. Of course, it cannot solve all problems, but it can solve most of the AWF blocking problems.
=> feat(client): http1 headers uppercase conversion by default

rnet.pyi, src/async_impl/response/http.rs, src/blocking/response/http.rs, src/blocking/response/ws.rs
close: https://github.com/0x676e67/rnet/issues/203
=> refactor(async_impl): Use async style for `Response.close()` to match async conventions

Cargo.toml, src/lib.rs
from: https://github.com/0x676e67/rnet/issues/222
According to the user-supplied test machine, Linux GNU, the result is: Essentially, this is an ABI explosion triggered by Linux ELF TLS model conflicts + dynamic load rule restrictions + compiler behavior union.
=> build(jemallocator): exclude dependency on Linux GNU targets
